micronaut:
  application:
    name: cdsi
  executors:
    enclave-jni:
      type: fixed
      # Note: this must never exceed `NumTCS` in `cds.conf`
      number-of-threads: 1
  metrics:
    enabled: true
    export:
      statsd:
        enabled: false
  server:
    netty:
      # don't compress
      compression-threshold: 1073741824  # 1G
      compression-level: 0

logger:
  levels:
    # The Cosmos client is pretty chatty
    com.azure.cosmos: WARN

endpoints:
  all:
    port: 8081

leakyBucketLimit:
  connections:
    bucket-size: 10
    leak-rate-scalar: 10
    leak-rate-duration: PT1M

tokenRateLimit:
  # 6 permits/hr -> 52560 permits per year
  bucket-size: 50000
  leak-rate-scalar: 6
  leak-rate-duration: PT1H

redis:
  uris: redis://localhost:6379

authentication:
  sharedSecret: Dx9/dxgdVWPazjTqCD6nMdAwS7pnnA5GsiM+aN4pQok=

enclave:
  enclaveId: dev
  availableEpcMemory: 32000000
  loadFactor: 1.6
  shards: 1
  token-secret: supersecretsquirrel
  simulated: true

accountTable:
  region: eu-west-2
  tableName: live_accounts
  streamName: cdsi-account-updates

# cosmos:
#   database: your-database-name
#   container: your-container-name
#   endpoint: "https://your-cosmos-instance.cosmos.azure.com:443"
#   key: your-cosmos-access-key